// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using infra.softline.Data;

#nullable disable

namespace infra.softline.Migrations
{
    [DbContext(typeof(ApiDBcontext))]
    [Migration("20260609233200_RemoveEmptySeedAndCreateAgain")]
    partial class RemoveEmptySeedAndCreateAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("domain.softline.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fantasia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = 0,
                            Documento = "",
                            Endereco = "",
                            Fantasia = "João Informática",
                            Nome = "João Carlos"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = 0,
                            Documento = "",
                            Endereco = "",
                            Fantasia = "Maria Tech",
                            Nome = "Maria Souza"
                        });
                });

            modelBuilder.Entity("domain.softline.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<decimal>("PesoBruto")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("PesoLiquido")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("ValorVenda")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = 101,
                            CodigoBarras = "7891234567890",
                            Descricao = "Notebook Dell Inspiron",
                            PesoBruto = 2.5m,
                            PesoLiquido = 2.0m,
                            ValorVenda = 3500.50m
                        },
                        new
                        {
                            Id = 2,
                            Codigo = 102,
                            CodigoBarras = "7891234567891",
                            Descricao = "Smartphone Samsung S23",
                            PesoBruto = 0.5m,
                            PesoLiquido = 0.4m,
                            ValorVenda = 4200.00m
                        },
                        new
                        {
                            Id = 3,
                            Codigo = 103,
                            CodigoBarras = "7891234567892",
                            Descricao = "Monitor LG 24 Polegadas",
                            PesoBruto = 3.2m,
                            PesoLiquido = 2.8m,
                            ValorVenda = 850.00m
                        });
                });

            modelBuilder.Entity("domain.softline.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
